apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # The Official Installation
  - https://github.com/cert-manager/cert-manager/releases/download/v1.14.4/cert-manager.yaml
  # Our Custom Configuration
  - cluster-issuer.yaml
